### ISSUE TITLE
GUI Improvement

### ISSUE THREAD

**Issue by KKhushhalR2405** [KKhushhalR2405/Translator_GUI#1]
Make GUI Responsive. 
For help, You can Refer to
1) [Window responsiveness](https://subscription.packtpub.com/book/application_development/9781788837460/7/ch07lvl1sec109/a-note-on-window-responsiveness)
2) [Responsive Grid](https://stackoverflow.com/questions/46522051/python-tkinter-responsive-grid)

**Comment by TheBlckCat** [comment]
Hi ✌️, 
Can you tell me more about this? What do you need? The code you have already does the translation so ... what do you need the GUI to do?

**Comment by KKhushhalR2405** [comment]
> Hi ✌️,
> Can you tell me more about this? What do you need? The code you have already does the translation so ... what do you need the GUI to do?

The current GUI has a window size of 200x70. So when I give a sentence containing 5-6 words or more, I have to manually increase the width. I want to increase the window size so as to fit large sentences. Just an ideal size, neither too big nor too small. 
(PS: If you can make a responsive size, It will be good.)
