### ISSUE TITLE
Increase Language Support

### ISSUE THREAD

**Issue by KKhushhalR2405** [KKhushhalR2405/Translator_GUI#2]
Add more language support.
Refer [here](https://py-googletrans.readthedocs.io/en/latest/) for all the languages supported by googletrans.

**Comment by TheBlckCat** [comment]
Hi ✌️,
I want to work on this issue

**Comment by KKhushhalR2405** [comment]
> Hi ✌️,
> I want to work on this issue

Yes, You can.
I need a dropdown menu containing a list of languages(preferably 3-5 languages) to select from. And then translate into that particular language. You can refer [here](https://stackoverflow.com/questions/45441885/how-can-i-create-a-dropdown-menu-from-a-list-in-tkinter) or can always ask for help. Thank You 💯

**Comment by KKhushhalR2405** [comment]
Select any languages of your choice.
